### ISSUE TITLE
support bound methods

### ISSUE THREAD

**Issue by jnoortheen** [igrek51/nuclear#1]
when a bound method is given for `run` argument, the following traceback appears

```
[2021-09-19 20:51:57] [WARN ] can't inject argument 'self' to function 'cd': name not found
Traceback (most recent call last):
  File "/src/shell/xsh/xonsh/procs/proxies.py", line 523, in run
    r = self.f(self.args, sp_stdin, sp_stdout, sp_stderr, spec, spec.stack)
        │      │          │         │          │          │     └ SubprocSpec(['commands'], ProcProxyThread, stdin=None, stdout=<_io.TextIOWrapper name=7 mode='w' encoding='UTF-8'>, stderr=<_io....
        │      │          │         │          │          └ SubprocSpec(['commands'], ProcProxyThread, stdin=None, stdout=<_io.TextIOWrapper name=7 mode='w' encoding='UTF-8'>, stderr=<_io....
        │      │          │         │          └ <_io.TextIOWrapper name=9 encoding='utf-8'>
        │      │          │         └ <_io.TextIOWrapper name=7 encoding='utf-8'>
        │      │          └ None
        │      └ <ProcProxyThread(Thread-27, started 140108367373888)>
        └ <ProcProxyThread(Thread-27, started 140108367373888)>
  File "/src/shell/xontribs/commands/xontrib/commands/dev_cmd.py", line 212, in __call__
    self.build.run_with_args(args)
    │                        └ ['commands']
    └ <xontrib.commands.dev_cmd.Alias object at 0x7f6d954af1c0>
  File "/home/noor/.virtualenvs/user-xsh-rVZlQJi1-py3.9/lib/python3.9/site-packages/nuclear/builder/builder.py", line 84, in run_with_args
    parser.parse_args(args)
    │                 └ ['commands']
    └ <nuclear.parser.parser.Parser object at 0x7f6d846ea1f0>
  File "/home/noor/.virtualenvs/user-xsh-rVZlQJi1-py3.9/lib/python3.9/site-packages/nuclear/parser/parser.py", line 88, in parse_args
    run_action(run_context.action, run_context.internal_vars)
    │          │                   └ RunContext(args_container=<nuclear.args.container.ArgsContainer object at 0x7f6d846ea2b0>, action=<bound method Alias.cd of <xon...
    │          └ RunContext(args_container=<nuclear.args.container.ArgsContainer object at 0x7f6d846ea2b0>, action=<bound method Alias.cd of <xon...
    └ <function run_action at 0x7f6d84595280>
  File "/home/noor/.virtualenvs/user-xsh-rVZlQJi1-py3.9/lib/python3.9/site-packages/nuclear/parser/inject.py", line 17, in run_action
    action(**kwargs)
    │        └ {'self': None, 'name': 'commands'}
    └ <bound method Alias.cd of <xontrib.commands.dev_cmd.Alias object at 0x7f6d954af1c0>>
TypeError: cd() got multiple values for argument 'self'
```

As of now, I am using static_method decorator. Is it possible to pass instance methods?

**Comment by igrek51** [comment]
Not sure how your code looks like, but here's an example how you can use nuclear with static methods or even class methods:
```python
#!/usr/bin/env python3
from nuclear import CliBuilder, subcommand

def main():
    CliBuilder().has(
        subcommand('static', run=Hello.static),
        subcommand('classy', run=lambda: Hello.classy()),
    ).run()

class Hello:
    @staticmethod
    def static():
        print('here comes the static')

    @classmethod
    def classy(cls):
        print('very classy')

main()
```
The following verifies that the methods are actually being called:
```
$ ./demo.py static
here comes the static
$ ./demo.py classy
very classy
```

**Comment by jnoortheen** [comment]
```
class Hello:
    @staticmethod
    def static():
        print('here comes the static')

    def instance(self):
        print('very classy')
    
    @cached_property
    def builder(self):
        return CliBuilder().has(
        subcommand('help', run=self.instance),
       )
```

![2021-09-20_19-04](https://user-images.githubusercontent.com/6702219/134011320-c4fd13ff-9b8e-4896-a5a8-40d3d0c0c1b6.png)

My code is similar to this. I am using this way to postpone building and wrap all data inside a single instance. I have just seen your inner codes, (adding the default arguments part), and they use the inner functions to wrap calls to instance methods. Also one small suggestion, using `inspect.signature` will return more relevant things in order to call

**Comment by igrek51** [comment]
Alright, now I see what you mean.
However this is not quite how `CliBuilder` is intended to be called as it loses `self` reference and `CliBuilder` is unable to find it from variables kept inside.

If you really want it so badly, you can convert one-argument function to zero-argument function with lambda:
```python
from functools import cached_property
from nuclear import CliBuilder, subcommand

class Hello:
    def instance(self):
        print('help me')
    
    @cached_property
    def builder(self):
        return CliBuilder().has(
            subcommand('help', run=lambda: self.instance()),
        )

Hello().builder.run()
```

**Comment by jnoortheen** [comment]
It would be tedious if the function has arguments, we have to repeat the same for the lambda. 

Will you accept any patch ? 

By the way, thanks for making this.

**Comment by igrek51** [comment]
Sure. I agree, it would be unnecessarily repetitive, though I guess the hardest part would be extracting `self` from the method reference. I'm afraid this might not be so easy in Python.

**Comment by jnoortheen** [comment]
> I guess the hardest part would be extracting `self` from the method reference. I'm afraid this might not be so easy in Python.

We don't need to pass the self variable since the function will hold reference to the bound method. If we use the inspect.signature it will return the correct signature needed to call the method.

**Comment by jnoortheen** [comment]
@igrek51 thanks a lot. I also wanted to ask about coloring the help/usage output? can this be made more configurable? with argparse one can pass the custom formatter class. (perhaps an another issue?)

**Comment by igrek51** [comment]
@jnoortheen The help output is not configurable at this moment. You can request that in the separate issue.
